// flow-typed signature: 542ed89cefb919efb9318ec979032245
// flow-typed version: <<STUB>>/create-jest-runner_v*.*.*/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'create-jest-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'create-jest-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'create-jest-runner/build/createJestRunner' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/fail' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/getRunner' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/index' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/pass.1' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/pass' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/run' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/skip' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/toTestResult' {
  declare module.exports: any;
}

declare module 'create-jest-runner/build/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'create-jest-runner/build/createJestRunner.js' {
  declare module.exports: $Exports<'create-jest-runner/build/createJestRunner'>;
}
declare module 'create-jest-runner/build/fail.js' {
  declare module.exports: $Exports<'create-jest-runner/build/fail'>;
}
declare module 'create-jest-runner/build/getRunner.js' {
  declare module.exports: $Exports<'create-jest-runner/build/getRunner'>;
}
declare module 'create-jest-runner/build/index.js' {
  declare module.exports: $Exports<'create-jest-runner/build/index'>;
}
declare module 'create-jest-runner/build/pass.1.js' {
  declare module.exports: $Exports<'create-jest-runner/build/pass.1'>;
}
declare module 'create-jest-runner/build/pass.js' {
  declare module.exports: $Exports<'create-jest-runner/build/pass'>;
}
declare module 'create-jest-runner/build/run.js' {
  declare module.exports: $Exports<'create-jest-runner/build/run'>;
}
declare module 'create-jest-runner/build/skip.js' {
  declare module.exports: $Exports<'create-jest-runner/build/skip'>;
}
declare module 'create-jest-runner/build/toTestResult.js' {
  declare module.exports: $Exports<'create-jest-runner/build/toTestResult'>;
}
declare module 'create-jest-runner/build/utils.js' {
  declare module.exports: $Exports<'create-jest-runner/build/utils'>;
}
